### ISSUE TITLE
pl_url retrieving wrong link

### ISSUE THREAD

**Issue by rodrigomontalegre** [cran/PL94171#1]
Hi, I'm using the packing to load some census data and the function pl_url() is retrieving a faulty link for Florida's census data.

**Comment by rodrigomontalegre** [comment]
Actually, it was just my computer. I've tried it out again with a new RStudio session and the function is downloading the data fine.

**Comment by rodrigomontalegre** [comment]
Actually, it was just my computer. I've tried it out again with a new RStudio session and the function is downloading the data fine.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
